# Generated by Django 5.1.5 on 2025-01-22 02:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Elemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.URLField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Generacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Monstruo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('icono', models.URLField(blank=True, max_length=1000, null=True)),
                ('max_size', models.IntegerField()),
                ('min_size', models.IntegerField()),
                ('clase', models.ManyToManyField(related_name='clase_monstruo', to='monsterapi.clase')),
                ('debilidad', models.ManyToManyField(related_name='debilidad_monstruo', to='monsterapi.elemento')),
                ('elemento', models.ManyToManyField(related_name='elemento_monstruo', to='monsterapi.elemento')),
                ('estado', models.ManyToManyField(related_name='estados_aplicados', to='monsterapi.estado')),
                ('generacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monsterapi.generacion')),
            ],
        ),
    ]
