# Generated by Django 5.1.5 on 2025-01-23 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0002_remove_monstruo_generacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monstruo',
            name='clase',
        ),
        migrations.AddField(
            model_name='monstruo',
            name='clase',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='monsterapi.clase'),
        ),
    ]
