# Generated by Django 5.1.5 on 2025-01-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0003_remove_monstruo_clase_monstruo_clase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monstruo',
            name='max_size',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='monstruo',
            name='min_size',
            field=models.FloatField(),
        ),
    ]
