# Generated by Django 5.1.5 on 2025-01-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monsterapi', '0004_alter_monstruo_max_size_alter_monstruo_min_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='monstruo',
            name='imagen',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
